name: 🐛 Bug Report
description: Create a report to help us improve the Language Server.
title: "[Bug]: "
labels: ["bug", "triage"]
body:
  - type: markdown
    attributes:
      value: |
        Thank you for taking the time to report an issue. Please be as specific as possible to help us resolve it quickly.
  
  - type: textarea
    id: description
    attributes:
      label: Bug Description
      description: A clear and concise description of what the bug is.
      placeholder: The LSP crashes when I try to trigger completion on a function signature...
    validations:
      required: true

  - type: textarea
    id: reproduction
    attributes:
      label: Steps to Reproduce
      description: Exact steps to reproduce the behavior.
      placeholder: |
        1. Open file 'example.vl'
        2. Type 'func '
        3. Press Ctrl+Space
        4. See error notification
    validations:
      required: true

  - type: textarea
    id: expected
    attributes:
      label: Expected Behavior
      description: What did you expect to happen?
      placeholder: A list of available functions should appear.
    validations:
      required: true

  - type: dropdown
    id: environment
    attributes:
      label: Operating System
      options:
        - macOS (Apple Silicon)
        - macOS (Intel)
        - Windows
        - Linux
    validations:
      required: true

  - type: input
    id: version
    attributes:
      label: LSP Version
      placeholder: v0.1.0
    validations:
      required: true

  - type: textarea
    id: logs
    attributes:
      label: Logs / Traceback
      description: Copy and paste the console output or editor output channel logs.
      render: shell
    validations:
      required: false

